language: go

go:
  - 1.8

env:
  - GOOS=darwin GOARCH=amd64

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y

install:
  - glide install
  - go install

before_script:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --deadline=5m --errors $(glide novendor)
  - go test -v $(glide novendor)

after_success: go build -v -ldflags "-X main.metadata=$TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api_key:
    secure: "Po7kNeczHOxgeGczSUHxg7bj2rpzD4jrhCdv5Vt2jevY6so9uK0QaM7fXvVhSRDZKsXce9+I+CpspCmOZNziQOJVQ+RUL0KTOoBYjcDg7Vv8R5xk5gPX2koEf/caT1PSikNYn7NlJK9n2eA1T51xoyGxXw3ZfrEbbFeQfyjt4t0bcjcnqkUSNgg/5PA22sNMTWvluoLSxW/AF33mi6R8beUHDO3+qDLYq04WEaSm/a5V+64MlJQP/p052PhIeYAAlrqXGZrt1HAL1BjfGgPzMnjBl0Qi8Fr27XQx963tQnjiaRTVT7J7O8n7z0sdNvfPlRw31hqvvmOw4ylPCkinUw4A+53/YRqdyIkZ9EeVePLNrsw+hRLS2IXGP+fvRYWEruGP7k9sY395/6eMofcvUOR+uV8ueVwiNT8nvLeQAHM75KfeLyYTseFojK+orLvjE0/exHbCRxSm32GnLGGcJFEpSuuzVT/TxQuxUaEwp/xRA6zyg9TZQQ6fwXZhwouZpvo8Jz9Hy9u3IaErRa7Lt9d/iw0kr5cnVT0g+cAkMbi9TVOECsmNIPTBA1EPcoxOPIywXCjKIrMc6T+OrkSVPncizDO+VqD1BOQ10SbG/3vrLyV52/+PDss6ZstVKcEFOpUlMMYp1BbOtzboCrnYaMI8DCp+x6OFeZVQfQAdHKM="
  file:
    - "minikube-nfs"
  skip_cleanup: true
  on:
    tags: true
    go: 1.8
